// Code generated by pggen. DO NOT EDIT.

package postgres

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	GroupByID(ctx context.Context, id int) (GroupByIDRow, error)
	// GroupByIDBatch enqueues a GroupByID query into batch to be executed
	// later by the batch.
	GroupByIDBatch(batch genericBatch, id int)
	// GroupByIDScan scans the result of an executed GroupByIDBatch query.
	GroupByIDScan(results pgx.BatchResults) (GroupByIDRow, error)

	IDByGroup(ctx context.Context, params IDByGroupParams) (int, error)
	// IDByGroupBatch enqueues a IDByGroup query into batch to be executed
	// later by the batch.
	IDByGroupBatch(batch genericBatch, params IDByGroupParams)
	// IDByGroupScan scans the result of an executed IDByGroupBatch query.
	IDByGroupScan(results pgx.BatchResults) (int, error)

	SelectYears(ctx context.Context) ([]int, error)
	// SelectYearsBatch enqueues a SelectYears query into batch to be executed
	// later by the batch.
	SelectYearsBatch(batch genericBatch)
	// SelectYearsScan scans the result of an executed SelectYearsBatch query.
	SelectYearsScan(results pgx.BatchResults) ([]int, error)

	SelectSpecsForYear(ctx context.Context, year int) ([]pgtype.Text, error)
	// SelectSpecsForYearBatch enqueues a SelectSpecsForYear query into batch to be executed
	// later by the batch.
	SelectSpecsForYearBatch(batch genericBatch, year int)
	// SelectSpecsForYearScan scans the result of an executed SelectSpecsForYearBatch query.
	SelectSpecsForYearScan(results pgx.BatchResults) ([]pgtype.Text, error)

	SelectNumsForYearAndSpec(ctx context.Context, year int, spec pgtype.Text) ([]int, error)
	// SelectNumsForYearAndSpecBatch enqueues a SelectNumsForYearAndSpec query into batch to be executed
	// later by the batch.
	SelectNumsForYearAndSpecBatch(batch genericBatch, year int, spec pgtype.Text)
	// SelectNumsForYearAndSpecScan scans the result of an executed SelectNumsForYearAndSpecBatch query.
	SelectNumsForYearAndSpecScan(results pgx.BatchResults) ([]int, error)
}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

var _ Querier = &DBQuerier{}

// genericConn is a connection to a Postgres database. This is usually backed by
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	// Query executes sql with args. If there is an error the returned Rows will
	// be returned in an error state. So it is allowed to ignore the error
	// returned from Query and handle it in Rows.
	Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)

	// QueryRow is a convenience wrapper over Query. Any error that occurs while
	// querying is deferred until calling Scan on the returned Row. That Row will
	// error with pgx.ErrNoRows if no rows are returned.
	QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row

	// Exec executes sql. sql can be either a prepared statement name or an SQL
	// string. arguments should be referenced positionally from the sql string
	// as $1, $2, etc.
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...interface{})
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return NewQuerierConfig(conn, QuerierConfig{})
}

type QuerierConfig struct {
	// DataTypes contains pgtype.Value to use for encoding and decoding instead
	// of pggen-generated pgtype.ValueTranscoder.
	//
	// If OIDs are available for an input parameter type and all of its
	// transitive dependencies, pggen will use the binary encoding format for
	// the input parameter.
	DataTypes []pgtype.DataType
}

// NewQuerierConfig creates a DBQuerier that implements Querier with the given
// config. conn is typically *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerierConfig(conn genericConn, cfg QuerierConfig) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver(cfg.DataTypes)}
}

// WithTx creates a new DBQuerier that uses the transaction to run all queries.
func (q *DBQuerier) WithTx(tx pgx.Tx) (*DBQuerier, error) {
	return &DBQuerier{conn: tx}, nil
}

// preparer is any Postgres connection transport that provides a way to prepare
// a statement, most commonly *pgx.Conn.
type preparer interface {
	Prepare(ctx context.Context, name, sql string) (sd *pgconn.StatementDescription, err error)
}

// PrepareAllQueries executes a PREPARE statement for all pggen generated SQL
// queries in querier files. Typical usage is as the AfterConnect callback
// for pgxpool.Config
//
// pgx will use the prepared statement if available. Calling PrepareAllQueries
// is an optional optimization to avoid a network round-trip the first time pgx
// runs a query if pgx statement caching is enabled.
func PrepareAllQueries(ctx context.Context, p preparer) error {
	if _, err := p.Prepare(ctx, groupByIDSQL, groupByIDSQL); err != nil {
		return fmt.Errorf("prepare query 'GroupByID': %w", err)
	}
	if _, err := p.Prepare(ctx, idbyGroupSQL, idbyGroupSQL); err != nil {
		return fmt.Errorf("prepare query 'IDByGroup': %w", err)
	}
	if _, err := p.Prepare(ctx, selectYearsSQL, selectYearsSQL); err != nil {
		return fmt.Errorf("prepare query 'SelectYears': %w", err)
	}
	if _, err := p.Prepare(ctx, selectSpecsForYearSQL, selectSpecsForYearSQL); err != nil {
		return fmt.Errorf("prepare query 'SelectSpecsForYear': %w", err)
	}
	if _, err := p.Prepare(ctx, selectNumsForYearAndSpecSQL, selectNumsForYearAndSpecSQL); err != nil {
		return fmt.Errorf("prepare query 'SelectNumsForYearAndSpec': %w", err)
	}
	return nil
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver(types []pgtype.DataType) *typeResolver {
	ci := pgtype.NewConnInfo()
	for _, typ := range types {
		if txt, ok := typ.Value.(textPreferrer); ok && typ.OID != unknownOID {
			typ.Value = txt.ValueTranscoder
		}
		ci.RegisterDataType(typ)
	}
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

const groupByIDSQL = `SELECT year, spec, num
FROM groups
WHERE id = $1;`

type GroupByIDRow struct {
	Year int         `json:"year"`
	Spec pgtype.Text `json:"spec"`
	Num  int         `json:"num"`
}

// GroupByID implements Querier.GroupByID.
func (q *DBQuerier) GroupByID(ctx context.Context, id int) (GroupByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "GroupByID")
	row := q.conn.QueryRow(ctx, groupByIDSQL, id)
	var item GroupByIDRow
	if err := row.Scan(&item.Year, &item.Spec, &item.Num); err != nil {
		return item, fmt.Errorf("query GroupByID: %w", err)
	}
	return item, nil
}

// GroupByIDBatch implements Querier.GroupByIDBatch.
func (q *DBQuerier) GroupByIDBatch(batch genericBatch, id int) {
	batch.Queue(groupByIDSQL, id)
}

// GroupByIDScan implements Querier.GroupByIDScan.
func (q *DBQuerier) GroupByIDScan(results pgx.BatchResults) (GroupByIDRow, error) {
	row := results.QueryRow()
	var item GroupByIDRow
	if err := row.Scan(&item.Year, &item.Spec, &item.Num); err != nil {
		return item, fmt.Errorf("scan GroupByIDBatch row: %w", err)
	}
	return item, nil
}

const idbyGroupSQL = `SELECT id::integer
FROM groups
WHERE year = $1
  AND spec = $2
  AND num = $3;`

type IDByGroupParams struct {
	Year int
	Spec pgtype.Text
	Num  int
}

// IDByGroup implements Querier.IDByGroup.
func (q *DBQuerier) IDByGroup(ctx context.Context, params IDByGroupParams) (int, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "IDByGroup")
	row := q.conn.QueryRow(ctx, idbyGroupSQL, params.Year, params.Spec, params.Num)
	var item int
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("query IDByGroup: %w", err)
	}
	return item, nil
}

// IDByGroupBatch implements Querier.IDByGroupBatch.
func (q *DBQuerier) IDByGroupBatch(batch genericBatch, params IDByGroupParams) {
	batch.Queue(idbyGroupSQL, params.Year, params.Spec, params.Num)
}

// IDByGroupScan implements Querier.IDByGroupScan.
func (q *DBQuerier) IDByGroupScan(results pgx.BatchResults) (int, error) {
	row := results.QueryRow()
	var item int
	if err := row.Scan(&item); err != nil {
		return item, fmt.Errorf("scan IDByGroupBatch row: %w", err)
	}
	return item, nil
}

const selectYearsSQL = `SELECT DISTINCT year::integer
from public.groups
ORDER BY year;`

// SelectYears implements Querier.SelectYears.
func (q *DBQuerier) SelectYears(ctx context.Context) ([]int, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SelectYears")
	rows, err := q.conn.Query(ctx, selectYearsSQL)
	if err != nil {
		return nil, fmt.Errorf("query SelectYears: %w", err)
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var item int
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectYears row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectYears rows: %w", err)
	}
	return items, err
}

// SelectYearsBatch implements Querier.SelectYearsBatch.
func (q *DBQuerier) SelectYearsBatch(batch genericBatch) {
	batch.Queue(selectYearsSQL)
}

// SelectYearsScan implements Querier.SelectYearsScan.
func (q *DBQuerier) SelectYearsScan(results pgx.BatchResults) ([]int, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query SelectYearsBatch: %w", err)
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var item int
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectYearsBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectYearsBatch rows: %w", err)
	}
	return items, err
}

const selectSpecsForYearSQL = `SELECT DISTINCT spec
from public.groups
WHERE year = $1
ORDER BY spec;`

// SelectSpecsForYear implements Querier.SelectSpecsForYear.
func (q *DBQuerier) SelectSpecsForYear(ctx context.Context, year int) ([]pgtype.Text, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SelectSpecsForYear")
	rows, err := q.conn.Query(ctx, selectSpecsForYearSQL, year)
	if err != nil {
		return nil, fmt.Errorf("query SelectSpecsForYear: %w", err)
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var item pgtype.Text
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectSpecsForYear row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectSpecsForYear rows: %w", err)
	}
	return items, err
}

// SelectSpecsForYearBatch implements Querier.SelectSpecsForYearBatch.
func (q *DBQuerier) SelectSpecsForYearBatch(batch genericBatch, year int) {
	batch.Queue(selectSpecsForYearSQL, year)
}

// SelectSpecsForYearScan implements Querier.SelectSpecsForYearScan.
func (q *DBQuerier) SelectSpecsForYearScan(results pgx.BatchResults) ([]pgtype.Text, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query SelectSpecsForYearBatch: %w", err)
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var item pgtype.Text
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectSpecsForYearBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectSpecsForYearBatch rows: %w", err)
	}
	return items, err
}

const selectNumsForYearAndSpecSQL = `SELECT num::integer
from public.groups
WHERE year = $1
  AND spec = $2
ORDER BY spec;`

// SelectNumsForYearAndSpec implements Querier.SelectNumsForYearAndSpec.
func (q *DBQuerier) SelectNumsForYearAndSpec(ctx context.Context, year int, spec pgtype.Text) ([]int, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "SelectNumsForYearAndSpec")
	rows, err := q.conn.Query(ctx, selectNumsForYearAndSpecSQL, year, spec)
	if err != nil {
		return nil, fmt.Errorf("query SelectNumsForYearAndSpec: %w", err)
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var item int
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectNumsForYearAndSpec row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectNumsForYearAndSpec rows: %w", err)
	}
	return items, err
}

// SelectNumsForYearAndSpecBatch implements Querier.SelectNumsForYearAndSpecBatch.
func (q *DBQuerier) SelectNumsForYearAndSpecBatch(batch genericBatch, year int, spec pgtype.Text) {
	batch.Queue(selectNumsForYearAndSpecSQL, year, spec)
}

// SelectNumsForYearAndSpecScan implements Querier.SelectNumsForYearAndSpecScan.
func (q *DBQuerier) SelectNumsForYearAndSpecScan(results pgx.BatchResults) ([]int, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query SelectNumsForYearAndSpecBatch: %w", err)
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var item int
		if err := rows.Scan(&item); err != nil {
			return nil, fmt.Errorf("scan SelectNumsForYearAndSpecBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close SelectNumsForYearAndSpecBatch rows: %w", err)
	}
	return items, err
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs if the results from QueryAllDataTypes aren't passed to
// NewQuerierConfig.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
