schedule-api:
   url: https://back.uksivt.com/api/v1
telegram:
   timeout: "2s"
cron-scheduler:
   cron: "30 * * * *"
logger:
   output:
      paths: ["stdout"]
      error-paths: ["stdout"]
      format: "console"
   level: "debug"