// Code generated by pggen. DO NOT EDIT.

package postgres

import (
	"context"
	"fmt"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

// Querier is a typesafe Go interface backed by SQL queries.
//
// Methods ending with Batch enqueue a query to run later in a pgx.Batch. After
// calling SendBatch on pgx.Conn, pgxpool.Pool, or pgx.Tx, use the Scan methods
// to parse the results.
type Querier interface {
	CreateChat(ctx context.Context, chatID int64) (CreateChatRow, error)
	// CreateChatBatch enqueues a CreateChat query into batch to be executed
	// later by the batch.
	CreateChatBatch(batch genericBatch, chatID int64)
	// CreateChatScan scans the result of an executed CreateChatBatch query.
	CreateChatScan(results pgx.BatchResults) (CreateChatRow, error)

	FindByTgID(ctx context.Context, chatID int64) (FindByTgIDRow, error)
	// FindByTgIDBatch enqueues a FindByTgID query into batch to be executed
	// later by the batch.
	FindByTgIDBatch(batch genericBatch, chatID int64)
	// FindByTgIDScan scans the result of an executed FindByTgIDBatch query.
	FindByTgIDScan(results pgx.BatchResults) (FindByTgIDRow, error)

	FindByID(ctx context.Context, id int64) (FindByIDRow, error)
	// FindByIDBatch enqueues a FindByID query into batch to be executed
	// later by the batch.
	FindByIDBatch(batch genericBatch, id int64)
	// FindByIDScan scans the result of an executed FindByIDBatch query.
	FindByIDScan(results pgx.BatchResults) (FindByIDRow, error)

	UpdateGroup(ctx context.Context, group pgtype.Text, chatID int64) (pgconn.CommandTag, error)
	// UpdateGroupBatch enqueues a UpdateGroup query into batch to be executed
	// later by the batch.
	UpdateGroupBatch(batch genericBatch, group pgtype.Text, chatID int64)
	// UpdateGroupScan scans the result of an executed UpdateGroupBatch query.
	UpdateGroupScan(results pgx.BatchResults) (pgconn.CommandTag, error)

	UndeleteChat(ctx context.Context, chatID int64) (pgconn.CommandTag, error)
	// UndeleteChatBatch enqueues a UndeleteChat query into batch to be executed
	// later by the batch.
	UndeleteChatBatch(batch genericBatch, chatID int64)
	// UndeleteChatScan scans the result of an executed UndeleteChatBatch query.
	UndeleteChatScan(results pgx.BatchResults) (pgconn.CommandTag, error)

	Delete(ctx context.Context, chatID int64) (pgconn.CommandTag, error)
	// DeleteBatch enqueues a Delete query into batch to be executed
	// later by the batch.
	DeleteBatch(batch genericBatch, chatID int64)
	// DeleteScan scans the result of an executed DeleteBatch query.
	DeleteScan(results pgx.BatchResults) (pgconn.CommandTag, error)
}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

var _ Querier = &DBQuerier{}

// genericConn is a connection to a Postgres database. This is usually backed by
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	// Query executes sql with args. If there is an error the returned Rows will
	// be returned in an error state. So it is allowed to ignore the error
	// returned from Query and handle it in Rows.
	Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)

	// QueryRow is a convenience wrapper over Query. Any error that occurs while
	// querying is deferred until calling Scan on the returned Row. That Row will
	// error with pgx.ErrNoRows if no rows are returned.
	QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row

	// Exec executes sql. sql can be either a prepared statement name or an SQL
	// string. arguments should be referenced positionally from the sql string
	// as $1, $2, etc.
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
}

// genericBatch batches queries to send in a single network request to a
// Postgres server. This is usually backed by *pgx.Batch.
type genericBatch interface {
	// Queue queues a query to batch b. query can be an SQL query or the name of a
	// prepared statement. See Queue on *pgx.Batch.
	Queue(query string, arguments ...interface{})
}

// NewQuerier creates a DBQuerier that implements Querier. conn is typically
// *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerier(conn genericConn) *DBQuerier {
	return NewQuerierConfig(conn, QuerierConfig{})
}

type QuerierConfig struct {
	// DataTypes contains pgtype.Value to use for encoding and decoding instead
	// of pggen-generated pgtype.ValueTranscoder.
	//
	// If OIDs are available for an input parameter type and all of its
	// transitive dependencies, pggen will use the binary encoding format for
	// the input parameter.
	DataTypes []pgtype.DataType
}

// NewQuerierConfig creates a DBQuerier that implements Querier with the given
// config. conn is typically *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
func NewQuerierConfig(conn genericConn, cfg QuerierConfig) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver(cfg.DataTypes)}
}

// WithTx creates a new DBQuerier that uses the transaction to run all queries.
func (q *DBQuerier) WithTx(tx pgx.Tx) (*DBQuerier, error) {
	return &DBQuerier{conn: tx}, nil
}

// preparer is any Postgres connection transport that provides a way to prepare
// a statement, most commonly *pgx.Conn.
type preparer interface {
	Prepare(ctx context.Context, name, sql string) (sd *pgconn.StatementDescription, err error)
}

// PrepareAllQueries executes a PREPARE statement for all pggen generated SQL
// queries in querier files. Typical usage is as the AfterConnect callback
// for pgxpool.Config
//
// pgx will use the prepared statement if available. Calling PrepareAllQueries
// is an optional optimization to avoid a network round-trip the first time pgx
// runs a query if pgx statement caching is enabled.
func PrepareAllQueries(ctx context.Context, p preparer) error {
	if _, err := p.Prepare(ctx, createChatSQL, createChatSQL); err != nil {
		return fmt.Errorf("prepare query 'CreateChat': %w", err)
	}
	if _, err := p.Prepare(ctx, findByTgIDSQL, findByTgIDSQL); err != nil {
		return fmt.Errorf("prepare query 'FindByTgID': %w", err)
	}
	if _, err := p.Prepare(ctx, findByIDSQL, findByIDSQL); err != nil {
		return fmt.Errorf("prepare query 'FindByID': %w", err)
	}
	if _, err := p.Prepare(ctx, updateGroupSQL, updateGroupSQL); err != nil {
		return fmt.Errorf("prepare query 'UpdateGroup': %w", err)
	}
	if _, err := p.Prepare(ctx, undeleteChatSQL, undeleteChatSQL); err != nil {
		return fmt.Errorf("prepare query 'UndeleteChat': %w", err)
	}
	if _, err := p.Prepare(ctx, deleteSQL, deleteSQL); err != nil {
		return fmt.Errorf("prepare query 'Delete': %w", err)
	}
	return nil
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver(types []pgtype.DataType) *typeResolver {
	ci := pgtype.NewConnInfo()
	for _, typ := range types {
		if txt, ok := typ.Value.(textPreferrer); ok && typ.OID != unknownOID {
			typ.Value = txt.ValueTranscoder
		}
		ci.RegisterDataType(typ)
	}
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

const createChatSQL = `INSERT INTO chats(chat_id)
VALUES ($1) RETURNING id, created_at;`

type CreateChatRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// CreateChat implements Querier.CreateChat.
func (q *DBQuerier) CreateChat(ctx context.Context, chatID int64) (CreateChatRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "CreateChat")
	row := q.conn.QueryRow(ctx, createChatSQL, chatID)
	var item CreateChatRow
	if err := row.Scan(&item.ID, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("query CreateChat: %w", err)
	}
	return item, nil
}

// CreateChatBatch implements Querier.CreateChatBatch.
func (q *DBQuerier) CreateChatBatch(batch genericBatch, chatID int64) {
	batch.Queue(createChatSQL, chatID)
}

// CreateChatScan implements Querier.CreateChatScan.
func (q *DBQuerier) CreateChatScan(results pgx.BatchResults) (CreateChatRow, error) {
	row := results.QueryRow()
	var item CreateChatRow
	if err := row.Scan(&item.ID, &item.CreatedAt); err != nil {
		return item, fmt.Errorf("scan CreateChatBatch row: %w", err)
	}
	return item, nil
}

const findByTgIDSQL = `SELECT id, chat_id, college_group, created_at, deleted_at
FROM chats
WHERE chat_id = $1;`

type FindByTgIDRow struct {
	ID           int64              `json:"id"`
	ChatID       int64              `json:"chat_id"`
	CollegeGroup pgtype.Text        `json:"college_group"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// FindByTgID implements Querier.FindByTgID.
func (q *DBQuerier) FindByTgID(ctx context.Context, chatID int64) (FindByTgIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindByTgID")
	row := q.conn.QueryRow(ctx, findByTgIDSQL, chatID)
	var item FindByTgIDRow
	if err := row.Scan(&item.ID, &item.ChatID, &item.CollegeGroup, &item.CreatedAt, &item.DeletedAt); err != nil {
		return item, fmt.Errorf("query FindByTgID: %w", err)
	}
	return item, nil
}

// FindByTgIDBatch implements Querier.FindByTgIDBatch.
func (q *DBQuerier) FindByTgIDBatch(batch genericBatch, chatID int64) {
	batch.Queue(findByTgIDSQL, chatID)
}

// FindByTgIDScan implements Querier.FindByTgIDScan.
func (q *DBQuerier) FindByTgIDScan(results pgx.BatchResults) (FindByTgIDRow, error) {
	row := results.QueryRow()
	var item FindByTgIDRow
	if err := row.Scan(&item.ID, &item.ChatID, &item.CollegeGroup, &item.CreatedAt, &item.DeletedAt); err != nil {
		return item, fmt.Errorf("scan FindByTgIDBatch row: %w", err)
	}
	return item, nil
}

const findByIDSQL = `SELECT id, chat_id, college_group, created_at, deleted_at
FROM chats
WHERE id = $1;`

type FindByIDRow struct {
	ID           int64              `json:"id"`
	ChatID       int64              `json:"chat_id"`
	CollegeGroup pgtype.Text        `json:"college_group"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// FindByID implements Querier.FindByID.
func (q *DBQuerier) FindByID(ctx context.Context, id int64) (FindByIDRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "FindByID")
	row := q.conn.QueryRow(ctx, findByIDSQL, id)
	var item FindByIDRow
	if err := row.Scan(&item.ID, &item.ChatID, &item.CollegeGroup, &item.CreatedAt, &item.DeletedAt); err != nil {
		return item, fmt.Errorf("query FindByID: %w", err)
	}
	return item, nil
}

// FindByIDBatch implements Querier.FindByIDBatch.
func (q *DBQuerier) FindByIDBatch(batch genericBatch, id int64) {
	batch.Queue(findByIDSQL, id)
}

// FindByIDScan implements Querier.FindByIDScan.
func (q *DBQuerier) FindByIDScan(results pgx.BatchResults) (FindByIDRow, error) {
	row := results.QueryRow()
	var item FindByIDRow
	if err := row.Scan(&item.ID, &item.ChatID, &item.CollegeGroup, &item.CreatedAt, &item.DeletedAt); err != nil {
		return item, fmt.Errorf("scan FindByIDBatch row: %w", err)
	}
	return item, nil
}

const updateGroupSQL = `UPDATE chats
SET college_group = $1
WHERE chat_id = $2;`

// UpdateGroup implements Querier.UpdateGroup.
func (q *DBQuerier) UpdateGroup(ctx context.Context, group pgtype.Text, chatID int64) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "UpdateGroup")
	cmdTag, err := q.conn.Exec(ctx, updateGroupSQL, group, chatID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query UpdateGroup: %w", err)
	}
	return cmdTag, err
}

// UpdateGroupBatch implements Querier.UpdateGroupBatch.
func (q *DBQuerier) UpdateGroupBatch(batch genericBatch, group pgtype.Text, chatID int64) {
	batch.Queue(updateGroupSQL, group, chatID)
}

// UpdateGroupScan implements Querier.UpdateGroupScan.
func (q *DBQuerier) UpdateGroupScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec UpdateGroupBatch: %w", err)
	}
	return cmdTag, err
}

const undeleteChatSQL = `UPDATE chats
SET deleted_at = NULL
where chat_id = $1;`

// UndeleteChat implements Querier.UndeleteChat.
func (q *DBQuerier) UndeleteChat(ctx context.Context, chatID int64) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "UndeleteChat")
	cmdTag, err := q.conn.Exec(ctx, undeleteChatSQL, chatID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query UndeleteChat: %w", err)
	}
	return cmdTag, err
}

// UndeleteChatBatch implements Querier.UndeleteChatBatch.
func (q *DBQuerier) UndeleteChatBatch(batch genericBatch, chatID int64) {
	batch.Queue(undeleteChatSQL, chatID)
}

// UndeleteChatScan implements Querier.UndeleteChatScan.
func (q *DBQuerier) UndeleteChatScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec UndeleteChatBatch: %w", err)
	}
	return cmdTag, err
}

const deleteSQL = `UPDATE chats
SET deleted_at = now()
WHERE chat_id = $1;`

// Delete implements Querier.Delete.
func (q *DBQuerier) Delete(ctx context.Context, chatID int64) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "Delete")
	cmdTag, err := q.conn.Exec(ctx, deleteSQL, chatID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query Delete: %w", err)
	}
	return cmdTag, err
}

// DeleteBatch implements Querier.DeleteBatch.
func (q *DBQuerier) DeleteBatch(batch genericBatch, chatID int64) {
	batch.Queue(deleteSQL, chatID)
}

// DeleteScan implements Querier.DeleteScan.
func (q *DBQuerier) DeleteScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec DeleteBatch: %w", err)
	}
	return cmdTag, err
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs if the results from QueryAllDataTypes aren't passed to
// NewQuerierConfig.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
